// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmBauZyl-Ck3IV0HcAQOsF36fawDPgo_A',
    appId: '1:652310077439:web:f2d7851be44187701551ca',
    messagingSenderId: '652310077439',
    projectId: 'khawo-fluuter-we',
    authDomain: 'khawo-fluuter-we.firebaseapp.com',
    storageBucket: 'khawo-fluuter-we.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0RT27FfG8-PgPkhpJyBecEhHDJhIEJDo',
    appId: '1:652310077439:android:f5011ffa3158307f1551ca',
    messagingSenderId: '652310077439',
    projectId: 'khawo-fluuter-we',
    storageBucket: 'khawo-fluuter-we.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmU34_nv8Ax55x1kwots05IF4T7cLmGww',
    appId: '1:652310077439:ios:e3e3d8f895ed863b1551ca',
    messagingSenderId: '652310077439',
    projectId: 'khawo-fluuter-we',
    storageBucket: 'khawo-fluuter-we.appspot.com',
    iosClientId: '652310077439-p0jhhk0ns7ktln7ts1ofseo9ffpclj8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.khawi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmU34_nv8Ax55x1kwots05IF4T7cLmGww',
    appId: '1:652310077439:ios:e3e3d8f895ed863b1551ca',
    messagingSenderId: '652310077439',
    projectId: 'khawo-fluuter-we',
    storageBucket: 'khawo-fluuter-we.appspot.com',
    iosClientId: '652310077439-p0jhhk0ns7ktln7ts1ofseo9ffpclj8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.khawi',
  );
}
